pipeline {
    agent any
    stages {

        stage('Stop & Remove Old Container') {
            steps {
                sh '''
                    echo "Stop & Remove Old Container"
                    docker stop frontend || true
                    docker rm frontend || true
                '''
            }
        }

        stage('Build Image') {
            steps {
                sh '''
                    echo "Building image..."
                    cd $WORKSPACE/Frontend && docker build -t frontend .
                '''
            }
        }

        stage('Run Container') {
            steps {
                sh '''
                    echo "Running container..."
                    docker run -d -p 9000:3000 --name frontend frontend
                '''
            }
        }

    }
}